apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloud-native-app-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: cloud-native-app
  endpoints:
    - port: web
      path: /metrics
      interval: 15s
